"""Unit tests for inject_status_table_into_readme pure helpers."""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.inject_status_table_into_readme import (
    extract_table_from_statuses,
    inject_into_readme,
)


def test_extract_table_from_statuses_empty():
    assert extract_table_from_statuses("") == ""
    assert extract_table_from_statuses("no table here") == ""


def test_extract_table_from_statuses_header_only():
    content = """# Title
| Repository | Workflow | Status | Last Run |
|------------|----------|--------|----------|
Updated: 2025-02-24 12:00:00 UTC
"""
    out = extract_table_from_statuses(content)
    assert "| Repository | Workflow | Status | Last Run |" in out
    assert "|------------|----------|--------|----------|" in out
    assert "Updated: 2025-02-24 12:00:00 UTC" in out
    assert "Title" not in out


def test_extract_table_from_statuses_skips_footnote():
    content = """| Repository | Workflow | Status | Last Run |
|------------|----------|--------|----------|
*Generated by workflow. Do not edit.*
Updated: 2025-02-24
"""
    out = extract_table_from_statuses(content)
    assert "*Generated" not in out
    assert "Updated: 2025-02-24" in out


def test_inject_into_readme_replaces_between_markers():
    readme = """# Repo
<!-- WORKFLOW_STATUS_TABLE -->
old content
<!-- /WORKFLOW_STATUS_TABLE -->
"""
    table = "| A | B | C | D |\nUpdated: now"
    out = inject_into_readme(readme, table)
    assert "old content" not in out
    assert "| A | B | C | D |" in out
    assert "Updated: now" in out
    assert "<!-- WORKFLOW_STATUS_TABLE -->" in out
    assert "<!-- /WORKFLOW_STATUS_TABLE -->" in out


def test_inject_into_readme_preserves_rest():
    readme = """# Repo
Intro.
<!-- WORKFLOW_STATUS_TABLE -->
placeholder
<!-- /WORKFLOW_STATUS_TABLE -->
Trailing.
"""
    out = inject_into_readme(readme, "| x | y | z | w |")
    assert out.startswith("# Repo")
    assert "Intro." in out
    assert "Trailing." in out
